name: Deploy to Netlify preprod on commits to Dev
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build site
        run: npm run build

      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: $
          NETLIFY_AUTH_TOKEN: $
        run: netlify deploy